require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - "config/rubocop/rails.yml"
  - "config/rubocop/rubocop.yml"
  - "config/rubocop/rspec.yml"

AllCops:
  TargetRubyVersion: 3.0.5
  TargetRailsVersion: 6.1.7.3
