version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.5
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: root
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: db 
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --path vendor/bundle

      - run:
          name: Setup Database
          command: bundle exec rake db:create db:migrate db:seed

      - run:
          name: Run rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  build:
    jobs:
      - build

